zuul:
  routes:
    httpbin:
      path: /**
      serviceId: httpbin
      stripPrefix: true

httpbin:
  ribbon:
    listOfServers: httpbin.org,eu.httpbin.org

ribbon:
  eureka:
    enabled: false

eureka:
  client:
    enabled: false