zuul:
  routes:
    my-service:
      path: /my-service/**
      serviceId: my-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
      security:
        user:
          password: ${eureka.password}

---
spring:
  eureka:
    instance:
      hostname: ${DOMAIN_NAME}
      nonSecurePort: 80
    password: ${EUREKA_USER_PASSWORD:password}